### ISSUE TITLE
Code base for DRew?

### ISSUE THREAD

**Issue by AdarshMJ** [toenshoff/LRGB#1]
Hi, thank you for this amazing code base. I wanted to ask in your paper you also report improved results for DRew, but the code base seems to be missing this?

**Comment by toenshoff** [comment]
Hey, the main credit goes to https://github.com/rampasek/GraphGPS and https://github.com/vijaydwivedi75/lrgb.
This repo is a fork of their work with some modifications.

[DRew](https://github.com/BenGutteridge/DRew) is not included in this repository and we did not conduct experiments with this method. The reported results are from their [paper](https://proceedings.mlr.press/v202/gutteridge23a/gutteridge23a.pdf).

**Comment by AdarshMJ** [comment]
Okay got it. Thank you :)
