### ISSUE TITLE
Performance Gap

### ISSUE THREAD

**Issue by jiaqingxie** [toenshoff/LRGB#2]
Hi. I tried your tuned GPS-noPE configurations on PascalVOC-SuperPixels. However it has shown a very bad performance from my side but I didnt know the reason. Specifically I chose those seeds for reproducing: 0, 7, 42, 100. The final average F1 was around 0.25. 

So here's the link of my training curve: https://wandb.ai/jiaqing/PEGT/reports/best-test_f1-24-04-02-10-42-51---Vmlldzo3MzgxNTEw

<img width="281" alt="1712047419775" src="https://github.com/toenshoff/LRGB/assets/55912913/6b1965f8-b202-4f89-9baf-8e655834ef54">

Could you please check that? Thanks!

Best, Jiaqing

**Comment by toenshoff** [comment]
In our experiments we did use LapPE for GPS on this dataset (See Table 3 in the Appendix).

Looks like the config in this repository is wrong, we will fix this.
Thank you for raising this issue.
