### ISSUE TITLE
channel wise normalization

### ISSUE THREAD

**Issue by jiaqingxie** [toenshoff/LRGB#3]
Hi. Jan. 

Sorry I didn't notice that you've applied channel wise normalization to PascalVOC and COCO. Where this normalization is implemented in the codebase? Thanks.

Best,
Jiaqing

**Comment by toenshoff** [comment]
Hey,

in the node feature encoders [here](https://github.com/toenshoff/LRGB/blob/b676f9572a0dbfeb76a3b2892583bdc42688d9ee/graphgps/encoder/voc_superpixels_encoder.py).

Regards,
Jan

**Comment by jiaqingxie** [comment]
Thanks!
